### ISSUE TITLE
Dataset available via the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [saifulhaq95/IndicIRSuite#1]
Very cool paper/dataset/models! You may already be planning for this but it would be great if the datasets would be shared on the Hugging Face Hub (happy to help with that if needed).

**Comment by saifulhaq-hyprbots** [comment]
Hi @davanstrien !
Models and Dataset will be shared on hugging face hub soon.

**Comment by saifulhaq95** [comment]
Hi @davanstrien !
Models and Dataset will be shared on hugging face hub soon.

**Comment by davanstrien** [comment]
@saifulhaq95 that's great to hear! Will keep an eye out for this 🤗

**Comment by saifulhaq95** [comment]
@davanstrien  
Dataset: https://huggingface.co/datasets/saifulhaq9/indicmarco
Model: https://huggingface.co/saifulhaq9/indiccolbert
